### PR TITLE
Xelah USFM editor integration

### PR DESCRIPTION
**Pull request by samueljd**
Usfm editor using Proskomma, Epitelete-Perf-Html and Xelah. issue #555

### CODE REVIEW

**Comment by Bobbykumar706584** [comment]
1. image
2.  image
3.  image

**Comment by samueljd** [comment]
1. `phosphor-react` is already present in package.json. 
2. `gotochapter` is fixed.
3. `sessionData` is not an error. a clean install and creating a new user should fix that.

**Comment by joelthe1** [comment]
Thanks @samueljd! Does merging this PR mean that an existing user in Ag cannot be used further and a new user needs to be created?

**Comment by samueljd** [comment]
Not essentially. It works for me even with old usernames. I was suggesting a quick fix for testing. 
I'll  test it  tomorrow and see if I can replicate it.
Moreover this PR has commits pertaining to the editor alone and it doesn't involve any of login or userprofile code. So if the error persists, it's either from a previous merge, or I've to take a deep look into the code.

**Comment by Bobbykumar706584** [comment]
@samueljd while creating the new year
image

**Pull request merged**
