### PR TITLE
Display current username  

### LINKED ISSUE #473: Show the currently logged in username in the topbar or top user menu.
Show the currently logged in username in the topbar or top user menu.

### PR DESCRIPTION
**Pull request by samueljd**
Display current username on the project list and project page. fixes #473

### CODE REVIEW

**Comment by Bobbykumar706584** [comment]
Screenshot from 2022-08-31 12-38-45
@samueljd  username is null/undefined and displaying the error you can see in the screenshot

**Comment by joelthe1** [comment]
@Bobbykumar706584 could you share a screen recording of the steps you are taking to see that error?

**Comment by samueljd** [comment]
@joelthe1 @Bobbykumar706584 I was able to reproduce the error. Will fix it.

**Comment by samueljd** [comment]
I've pushed the fix for the username undefined error.

**Comment by Bobbykumar706584** [comment]
thank you @samueljd

**Pull request merged**
